<?php

return [
    'folder' => [
        'root' => '/',
        'upload' => '/images/upload/',
        'cms' => '/images/upload/cms/',
        'post' => '/images/upload/post/',
        'category' => '/images/upload/category/',
        'productcategory' => '/images/upload/productcategory/',
        'product' => '/images/upload/product/',
        'page' => '/images/upload/page/',
        'slide' => '/images/upload/slide/',
        'banner' => '/images/upload/banner/',
        'question' => '/images/upload/question/',
    ],
    'url' => [
        'category' => '/danh-muc/',
        'post' => '/tin-tuc/'
    ],

    'method-payments' => [
      "1" => "COD",
      "2" => "Internet Banking",
      "3" => "VISA, MASTERCARD",
      "4" => "Chuyển Khoản Ngân Hàng"
    ],

    'pageException' => [
        'giao-hang',
        'cam-ket',
        'about-us',
        'discount'
    ],

    'country' => [
        '1' => "An Giang",
        '6' => "Bà Rịa–Vũng Tàu",
        '2' => "Bắc Giang",
        '3' => "Bắc Kạn",
        '4' => "Bạc Liêu",
        '5' => "Bắc Ninh",
        '7' => "Bến Tre",
        '9' => "Bình Dương",
        '10' => "Bình Phước",
        '11' => "Bình Thuận",
        '8' => "Bình Định",
        '12' => "Cà Mau",
        '13' => "Cần Thơ",
        '14' => "Cao Bằng",
        '21' => "Gia Lai",
        '22' => "Hà Giang",
        '23' => "Hà Nam",
        '27' => "Hà Nội",
        '24' => "Hà Tĩnh",
        '25' => "Hải Dương",
        '26' => "Hải Phòng",
        '28' => "Hậu Giang",
        '30' => "Hồ Chí Minh",
        '29' => "Hòa Bình",
        '31' => "Hưng Yên",
        '32' => "Khánh Hòa",
        '33' => "Kiên Giang",
        '34' => "Kon Tum",
        '35' => "Lai Châu",
        '36' => "Lâm Đồng",
        '37' => "Lạng Sơn",
        '38' => "Lào Cai",
        '39' => "Long An",
        '40' => "Nam Định",
        '41' => "Nghệ An",
        '42' => "Ninh Bình",
        '43' => "Ninh Thuận",
        '44' => "Phú Thọ",
        '45' => "Phú Yên",
        '46' => "Quảng Bình",
        '47' => "Quảng Nam",
        '48' => "Quảng Ngãi",
        '49' => "Quảng Ninh",
        '50' => "Quảng Trị",
        '51' => "Sóc Trăng",
        '52' => "Sơn La",
        '53' => "Tây Ninh",
        '54' => "Thái Bình",
        '55' => "Thái Nguyên",
        '56' => "Thanh Hóa",
        '57' => "Thừa Thiên–Huế",
        '58' => "Tiền Giang",
        '59' => "Trà Vinh",
        '60' => "Tuyên Quang",
        '61' => "Vĩnh Long",
        '62' => "Vĩnh Phúc",
        '63' => "Yên Bái",
        '15' => "Đà Nẵng",
        '16' => "Đắk Lắk",
        '17' => "Đắk Nông ",
        '18' => "Điện Biên",
        '19' => "Đồng Nai ",
        '20' => "Đồng Tháp",
    ]
];
